media:  # table of every file known about
  id:          INTEGER PRIMARY KEY
  path:        TEXT UNIQUE  # abs path on disk
  added:       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  is_dir:      BOOLEAN DEFAULT 0
  byte_size:   INTEGER DEFAULT 0
  favorite:    INTEGER NOT NULL DEFAULT 0
  weight:      REAL
  artist:      TEXT
  type:        TEXT NOT NULL

variants:  # 'stacks' of related images
  base_id:     INTEGER  # ref media.id  (rank == 0)
  variant_id:  INTEGER  # ref media.id
  rank:        INTEGER DEFAULT 0  # 0 = base; 1,2,... = alternates
  UNIQUE:      [variant_id]

presets: # saved zoom / pan rectangles
  id:          INTEGER PRIMARY KEY
  group_id:    TEXT
  media_id:    INTEGER  # NULL folder-level default
  name:        TEXT  # "Profile-crop", etc.
  zoom:        REAL # e.g. 1.75
  pan_x:       INTEGER
  pan_y:       INTEGER
  is_default:  INTEGER
  hotkey:      TEXT

tags:  # free-form keywords
  media_id:   INTEGER  # media.id
  tag:        TEXT
  UNIQUE:     [media_id, tag]
  INDEX:      tag

comments:
  id:         INTEGER PRIMARY KEY
  media_id:   INTEGER NOT NULL
  created:    TIMESTAMP DEFAULT
  text:       TEXT NOT NULL
  seq:        INTEGER